version: '3.8'

services:

  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: tiendastock_app
    restart: unless-stopped
    ports:
      - "8080:80"
    working_dir: /var/www/html
    volumes:
      - ./src:/var/www/html
    networks:
      - tiendastock_network
    depends_on:
      - db
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html/public

  db:
    image: mysql:8.0
    container_name: tiendastock_mysql
    restart: unless-stopped
    ports:
      - "3307:3306"
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - tiendastock_mysql_data:/var/lib/mysql
    networks:
      - tiendastock_network

networks:
  tiendastock_network:
    driver: bridge

volumes:
  tiendastock_mysql_data: